# Generated by Django 6.0.2 on 2026-03-03 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTEA_Project_API', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField(default=30)),
                ('piso', models.IntegerField(default=1)),
                ('tipo', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en-uso', 'En uso'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('domicilio', models.TextField(blank=True, default='')),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('pisos', models.IntegerField(default=1)),
                ('notas', models.TextField(blank=True, default='')),
                ('instalaciones', models.JSONField(blank=True, default=list)),
                ('activa', models.BooleanField(default=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('imagen_portada', models.URLField(blank=True, default='')),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('fecha_fin', models.DateField()),
                ('hora_fin', models.TimeField()),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], default='Presencial', max_length=20)),
                ('cupo_maximo', models.IntegerField(default=30)),
                ('costo_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lista_espera', models.BooleanField(default=False)),
                ('publicar_inmediatamente', models.BooleanField(default=True)),
                ('es_organizador', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Borrador', 'Borrador'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Borrador', max_length=20)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='GTEA_Project_API.aulas')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='GTEA_Project_API.categorias')),
                ('organizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='GTEA_Project_API.sedes')),
            ],
        ),
        migrations.AddField(
            model_name='aulas',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='GTEA_Project_API.sedes'),
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('inscrito', 'Inscrito'), ('lista_espera', 'Lista de espera')], default='inscrito', max_length=20)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='GTEA_Project_API.alumnos')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='GTEA_Project_API.eventos')),
            ],
            options={
                'unique_together': {('evento', 'alumno')},
            },
        ),
    ]
